version: "3.3"

services:

  ibama:
    build: ./ibama
    image: appibama_ibama
    networks:
      - deploy_network
    container_name: ibama
    volumes:
      - ./volumes:/ibama/files

  flask:
    build: ./flask
    depends_on:
      - ibama
    image: appibama_flask
    container_name: flask
    networks:
      - deploy_network
    environment:
      - APP_NAME=Myapp
    expose:
      - 8080
    volumes:
      - ./volumes:/app/volume

  nginx:
    build: ./nginx
    depends_on:
      - ibama
    image: appibama_nginx
    networks:
      - deploy_network
    container_name: nginx
    ports:
      - "8081:8081"

networks:
  deploy_network:
    driver: bridge